### ISSUE TITLE
Interactive plots

### ISSUE THREAD

**Issue by filipsch** [trestletech/shinyAce#22] opened 2014-12-11 16:46 UTC
Hi,

Do you think there is any way to extend the shinyui example to allow the coding of dynamic ggvis plots? This would mean an actual shiny app with controls and corresponding callbacks inside the shiny app that houses the ace editor etc.

I tried to extend the example:
```{r}
# server.R
library(ggvis) 
library(shiny)
library(shinyAce)

shinyServer(function(input, output, session) {
  r_gv <- reactive({
    input$eval
    isolate(eval(parse(text=input$code)))
  }) 
  bind_shiny(r_gv, plot_id = "ggvis_plot", controls_id = "ggvis_control", session = session) 
})
```
```{r}
# ui.R
library(ggvis)
library(shiny)
library(shinyAce)

#' Define UI for application that demonstrates a simple Ace editor
#' @author Jeff Allen \email{jeff@@trestletech.com}
shinyUI(
  bootstrapPage(div(
    class="container-fluid",
    div(class="row-fluid",
        div(class="span6",
            h2("UI Code"),  
            aceEditor("code", mode="r", value='
mtcars %>% 
  ggvis(~mpg, ~wt, fill := input_radiobuttons(label = "Choose color:", choices = c("black","red","blue","green"))) %>%
  layer_points()
'),
            actionButton("eval", "Update UI")
        ),
        div(class="span6",
            h2("Coded ggvis plot"),
            div(class="well", uiOutput("ggvis_control")),
            ggvisOutput("ggvis_plot")
        )
    )
  )))
```

The default code in the editor leads to an app that displays and reacts correctly. However, when you change the code and press submit again, the graphic does not respond to the control widgets anymore.

Any ideas here?

Thanks

**Comment by trestletech** [comment] 2015-01-14 04:43
Hi. Sorry I'm just now getting a chance to look at this.

Unfortunately I have no idea what the problem is here, but it looks like something that would be addressed in Shiny or, more likely, in ggvis. You may have better luck posting on one of those mailing lists.

I'll close this issue for now, but do feel free to reopen it if you feel like there's an issue on the ShinyAce side of things.

**Closed by trestletech** 2015-01-14 04:43 UTC
